name: CI Tests

on:
  push:
    branches: ["main", "dev"]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential libffi-dev

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set environment variables
        env:
          USERS: ${{ secrets.USERS }}
          DEVICES: ${{ vars.DEVICES }}
          PRESETS_PATH: ${{ vars.PRESETS_PATH }}
          UTILS_PATH: ${{ vars.UTILS_PATH }}
          SUPER_SECRET_KEY: ${{ secrets.SUPER_SECRET_KEY }}
        run: |
          echo "Environment variables have been set."

      - name: Run Unit Tests
        env:
          USERS: ${{ secrets.USERS }}
          DEVICES: ${{ vars.DEVICES }}
          PRESETS_PATH: ${{ vars.PRESETS_PATH }}
          UTILS_PATH: ${{ vars.UTILS_PATH }}
          SUPER_SECRET_KEY: ${{ secrets.SUPER_SECRET_KEY }}
        run: |
          bash .github/workflows/unit_tests.sh

      - name: Upload Test Results (Optional)
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: ./test-results/
